# The goal, to be sent by the client
sensor_msgs/Image target_image
---
# The result, to be sent by the server upon completion
bool is_stabilized
---
# The feedback, to be sent periodically by the server during execution
float32 drone_linear_velocity
float32 drone_yaw_velocity
