# The goal, to be sent by the client
# The target pose (with respect to the platform frame)
# you want the drone pose to matche with
geometry_msgs/TransformStamped target_pose
---
# The result, to be sent by the server upon completion
bool is_drone_stabilized
---
# The feedback, to be sent periodically by the server during execution
# float32 drone_linear_velocity
# float32 drone_yaw_velocity
float32 error
