mobile_platform:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position controllers
  tx_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: tx_joint
  
  ty_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: ty_joint

  tz_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: tz_joint

  roll_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: roll_joint

  pitch_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: pitch_joint

  yaw_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: yaw_joint

  gazebo_ros_control/pid_gains:
    tx_joint:
      p: 10.0
      i: 0.01
      d: 1.0

    ty_joint:
      p: 10.0
      i: 0.01
      d: 1.0
      
    tz_joint:
      p: 10.0
      i: 0.01
      d: 1.0

    roll_joint:
      p: 10.0
      i: 0.01
      d: 1.0

    pitch_joint:
      p: 10.0
      i: 0.01
      d: 1.0

    yaw_joint:
      p: 10.0
      i: 0.01
      d: 1.0
